apiVersion: v1
kind: Service
metadata:
  name: kxdemo-nodeport-service
spec:
  selector:
    app: kxdemo-app
  type: NodePort  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30036