apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kxdemo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/aashu-anblicks/kxsession.git
    targetRevision: HEAD
    path: argo/example-app
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kxdemo-app
  syncPolicy:
    automated:
      prune: false
      selfHeal: false