apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mytechtalk-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/aashu-anblicks/techtalk.git
    targetRevision: HEAD
    path: argo/example-app
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: mytechtalk-app
  syncPolicy:
    automated:
      prune: false
      selfHeal: false